ALTER TABLE "${schema}"."CDS_SOGGETTO_SERVIZIO" ADD CONSTRAINT "PK_CDS_SOGGETTO_SERVIZIO" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."PK_CDS_SOGGETTO_SERVIZIO" ON "${schema}"."CDS_SOGGETTO_SERVIZIO" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."PSP" ADD CONSTRAINT "PK_PSP" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."PK_PSP" ON "${schema}"."PSP" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 254
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."PSP" ADD CONSTRAINT "UQ_ID_PSP" UNIQUE ("ID_PSP")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."UQ_ID_PSP" ON "${schema}"."PSP" ("ID_PSP")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."CONFIGURATION_KEYS" ADD CONSTRAINT "UQ_CONFIGURATION_KEYS" UNIQUE ("CONFIG_CATEGORY", "CONFIG_KEY")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."UQ_CONFIGURATION_KEYS" ON "${schema}"."CONFIGURATION_KEYS" ("CONFIG_CATEGORY", "CONFIG_KEY")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."PDD" ADD CONSTRAINT "PK_PDD" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."PK_PDD" ON "${schema}"."PDD" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."PDD" ADD CONSTRAINT "UQ_PDD" UNIQUE ("ID_PDD")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."UQ_PDD" ON "${schema}"."PDD" ("ID_PDD")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."AUTH_PERMISSIONS" ADD CONSTRAINT "PK_AUTH_PERMISSIONS" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."PK_AUTH_PERMISSIONS" ON "${schema}"."AUTH_PERMISSIONS" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."INFORMATIVE_CONTO_ACCREDITO_MASTER" ADD CONSTRAINT "PK_INFORMATIVE_CONTO_ACCREDITO_MASTER" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."PK_INFORMATIVE_CONTO_ACCREDITO_MASTER" ON "${schema}"."INFORMATIVE_CONTO_ACCREDITO_MASTER" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."INFORMATIVE_CONTO_ACCREDITO_MASTER" ADD CONSTRAINT "UQ_INFORMATIVA_CONTO_ACCREDITO" UNIQUE ("FK_PA", "ID_INFORMATIVA_CONTO_ACCREDITO_PA")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."UQ_INFORMATIVA_CONTO_ACCREDITO" ON "${schema}"."INFORMATIVE_CONTO_ACCREDITO_MASTER" ("FK_PA", "ID_INFORMATIVA_CONTO_ACCREDITO_PA")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."INTERMEDIARI_PA" ADD CONSTRAINT "PK_INTERMEDIARI_PA" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."PK_INTERMEDIARI_PA" ON "${schema}"."INTERMEDIARI_PA" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."INTERMEDIARI_PA" ADD CONSTRAINT "UQ_ID_INTERMEDIARIO_PA" UNIQUE ("ID_INTERMEDIARIO_PA")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."UQ_ID_INTERMEDIARIO_PA" ON "${schema}"."INTERMEDIARI_PA" ("ID_INTERMEDIARIO_PA")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."WFESP_PLUGIN_CONF" ADD CONSTRAINT "UQ_ID_SERV_PLUGIN" UNIQUE ("ID_SERV_PLUGIN")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."UQ_ID_SERV_PLUGIN" ON "${schema}"."WFESP_PLUGIN_CONF" ("ID_SERV_PLUGIN")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."WFESP_PLUGIN_CONF" ADD CONSTRAINT "PK_WFESP_PLUGIN_CONF" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."PK_WFESP_PLUGIN_CONF" ON "${schema}"."WFESP_PLUGIN_CONF" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."CODIFICHE" ADD CONSTRAINT "PK_CODIFICHE" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."PK_CODIFICHE" ON "${schema}"."CODIFICHE" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."CODIFICHE" ADD CONSTRAINT "UQ_ID_CODIFICA" UNIQUE ("ID_CODIFICA")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."UQ_ID_CODIFICA" ON "${schema}"."CODIFICHE" ("ID_CODIFICA")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."INFORMATIVE_PA_FASCE" ADD CONSTRAINT "PK_INFORMATIVE_PA_FASCE" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."PK_INFORMATIVE_PA_FASCE" ON "${schema}"."INFORMATIVE_PA_FASCE" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."CDI_INFORMAZIONI_SERVIZIO" ADD CONSTRAINT "PK_CDI_INFORMAZIONI_SERVIZIO" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."PK_CDI_INFORMAZIONI_SERVIZIO" ON "${schema}"."CDI_INFORMAZIONI_SERVIZIO" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."TEMPLATE_MARKDOWN" ADD CONSTRAINT "UQ_TEMPLATE_MARKDOWN" UNIQUE ("NAME")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."UQ_TEMPLATE_MARKDOWN" ON "${schema}"."TEMPLATE_MARKDOWN" ("NAME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" )  ENABLE;
ALTER TABLE "${schema}"."SYNC_STATUS" ADD CONSTRAINT "PK_SYNC_STATUS" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."PK_SYNC_STATUS" ON "${schema}"."SYNC_STATUS" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."INTERMEDIARI_PSP" ADD CONSTRAINT "UQ_ID_INTERMEDIARIO_PSP" UNIQUE ("ID_INTERMEDIARIO_PSP")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."UQ_ID_INTERMEDIARIO_PSP" ON "${schema}"."INTERMEDIARI_PSP" ("ID_INTERMEDIARIO_PSP")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."INTERMEDIARI_PSP" ADD CONSTRAINT "PK_INTERMEDIARI_PSP" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."PK_INTERMEDIARI_PSP" ON "${schema}"."INTERMEDIARI_PSP" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."CANALI_NODO" ADD CONSTRAINT "PK_CANALI_NODO" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."PK_CANALI_NODO" ON "${schema}"."CANALI_NODO" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."BINARY_FILE" ADD CONSTRAINT "PK_BINARY_FILE" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."PK_BINARY_FILE" ON "${schema}"."BINARY_FILE" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."PSP_CANALE_TIPO_VERSAMENTO" ADD CONSTRAINT "PK_PSP_CANALE_TIPO_VERSAMENTO" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."PK_PSP_CANALE_TIPO_VERSAMENTO" ON "${schema}"."PSP_CANALE_TIPO_VERSAMENTO" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."STAZIONI" ADD CONSTRAINT "PK_STAZIONI" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."PK_STAZIONI" ON "${schema}"."STAZIONI" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."STAZIONI" ADD CONSTRAINT "UQ_ID_STAZIONE" UNIQUE ("ID_STAZIONE")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."UQ_ID_STAZIONE" ON "${schema}"."STAZIONI" ("ID_STAZIONE")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."AUTH_ROLES" ADD CONSTRAINT "PK_AUTH_ROLES" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."PK_AUTH_ROLES" ON "${schema}"."AUTH_ROLES" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."CDI_MASTER" ADD CONSTRAINT "UQ_INFORMATIVA_CDI" UNIQUE ("FK_PSP", "ID_INFORMATIVA_PSP")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."UQ_INFORMATIVA_CDI" ON "${schema}"."CDI_MASTER" ("FK_PSP", "ID_INFORMATIVA_PSP")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."CDI_MASTER" ADD CONSTRAINT "PK_CDI_MASTER" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."PK_CDI_MASTER" ON "${schema}"."CDI_MASTER" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."CDI_FASCIA_COSTO_SERVIZIO" ADD CONSTRAINT "PK_CDI_FASCIA_COSTO_SERVIZIO" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."PK_CDI_FASCIA_COSTO_SERVIZIO" ON "${schema}"."CDI_FASCIA_COSTO_SERVIZIO" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."QUADRATURE_SCHED" ADD CONSTRAINT "PK_QUADRATURE_SCHED" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."PK_QUADRATURE_SCHED" ON "${schema}"."QUADRATURE_SCHED" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."CANALI" ADD CONSTRAINT "PK_CANALI" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."PK_CANALI" ON "${schema}"."CANALI" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."CANALI" ADD CONSTRAINT "UQ_ID_CANALE" UNIQUE ("ID_CANALE")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."UQ_ID_CANALE" ON "${schema}"."CANALI" ("ID_CANALE")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."AUTH_USERS" ADD CONSTRAINT "PK_AUTH_USERS" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."PK_AUTH_USERS" ON "${schema}"."AUTH_USERS" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."DENYLIST" ADD CONSTRAINT "PK_DENYLIST" PRIMARY KEY ("FK_PSP", "FK_CANALE", "FK_PA")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."PK_DENYLIST" ON "${schema}"."DENYLIST" ("FK_PSP", "FK_CANALE", "FK_PA")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  TABLESPACE "${tablespaceData}" )  ENABLE;
ALTER TABLE "${schema}"."CDS_SERVIZIO" ADD CONSTRAINT "PK_CDS_SERVIZIO" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."PK_CDS_SERVIZIO" ON "${schema}"."CDS_SERVIZIO" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."CDI_DETAIL" ADD CONSTRAINT "PK_CDI_DETAIL" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."PK_CDI_DETAIL" ON "${schema}"."CDI_DETAIL" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."PA_STAZIONE_PA" ADD CONSTRAINT "PK_PA_STAZIONE_PA" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."PK_PA_STAZIONE_PA" ON "${schema}"."PA_STAZIONE_PA" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."CDI_PREFERENCES" ADD CONSTRAINT "PK__CDI_PREF__755589F03429BB53" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."PK__CDI_PREF__755589F03429BB53" ON "${schema}"."CDI_PREFERENCES" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."CDS_SOGGETTO" ADD CONSTRAINT "PK_CDS_SOGGETTO" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."PK_CDS_SOGGETTO" ON "${schema}"."CDS_SOGGETTO" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."INFORMATIVE_PA_MASTER" ADD CONSTRAINT "PK_INFORMATIVE_PA_MASTER" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."PK_INFORMATIVE_PA_MASTER" ON "${schema}"."INFORMATIVE_PA_MASTER" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."INFORMATIVE_PA_MASTER" ADD CONSTRAINT "UQ_INFORMATIVA_PA" UNIQUE ("FK_PA", "ID_INFORMATIVA_PA")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."UQ_INFORMATIVA_PA" ON "${schema}"."INFORMATIVE_PA_MASTER" ("FK_PA", "ID_INFORMATIVA_PA")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."INFORMATIVE_CONTO_ACCREDITO_DETAIL" ADD CONSTRAINT "PK_INFORMATIVE_CONTO_ACCREDITO_DETAIL" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."PK_INFORMATIVE_CONTO_ACCREDITO_DETAIL" ON "${schema}"."INFORMATIVE_CONTO_ACCREDITO_DETAIL" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."ELENCO_SERVIZI" ADD CONSTRAINT "PK_ELENCO_SERVIZI" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."PK_ELENCO_SERVIZI" ON "${schema}"."ELENCO_SERVIZI" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."CANALE_TIPO_VERSAMENTO" ADD CONSTRAINT "PK_CANALE_TIPO_VERSAMENTOE" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."PK_CANALE_TIPO_VERSAMENTOE" ON "${schema}"."CANALE_TIPO_VERSAMENTO" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."FTP_SERVERS" ADD CONSTRAINT "PK__FTP_SERV__755589F079FD19BE" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."PK__FTP_SERV__755589F079FD19BE" ON "${schema}"."FTP_SERVERS" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."CODIFICHE_PA" ADD CONSTRAINT "PK_CODIFICHE_PA" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."PK_CODIFICHE_PA" ON "${schema}"."CODIFICHE_PA" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."INFORMATIVE_PA_DETAIL" ADD CONSTRAINT "PK_INFORMATIVE_PA_DETAIL" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."PK_INFORMATIVE_PA_DETAIL" ON "${schema}"."INFORMATIVE_PA_DETAIL" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."TIPI_VERSAMENTO" ADD CONSTRAINT "UQ_TIPO_VERSAMENTO" UNIQUE ("TIPO_VERSAMENTO")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."UQ_TIPO_VERSAMENTO" ON "${schema}"."TIPI_VERSAMENTO" ("TIPO_VERSAMENTO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."TIPI_VERSAMENTO" ADD CONSTRAINT "PK_TIPI_VERSAMENTO" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."PK_TIPI_VERSAMENTO" ON "${schema}"."TIPI_VERSAMENTO" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."PA" ADD CONSTRAINT "UQ_ID_DOMINIO" UNIQUE ("ID_DOMINIO")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."UQ_ID_DOMINIO" ON "${schema}"."PA" ("ID_DOMINIO")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
ALTER TABLE "${schema}"."PA" ADD CONSTRAINT "PK_PA" PRIMARY KEY ("OBJ_ID")
  USING INDEX (CREATE UNIQUE INDEX "${schema}"."PK_PA" ON "${schema}"."PA" ("OBJ_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceIdx}" )  ENABLE;
-- new object type path: SCHEMA_EXPORT/TABLE/CONSTRAINT/REF_CONSTRAINT
ALTER TABLE "${schema}"."CDS_SOGGETTO_SERVIZIO" ADD CONSTRAINT "FK_CDS_SOGGETTO_SERVIZIO_TO_CDS_SERVIZIO" FOREIGN KEY ("FK_CDS_SERVIZIO")
	  REFERENCES "${schema}"."CDS_SERVIZIO" ("OBJ_ID") ENABLE;
ALTER TABLE "${schema}"."CDS_SOGGETTO_SERVIZIO" ADD CONSTRAINT "FK_CDS_SOGGETTO_SERVIZIO_TO_CDS_SOGGETTO" FOREIGN KEY ("FK_CDS_SOGGETTO")
	  REFERENCES "${schema}"."CDS_SOGGETTO" ("OBJ_ID") ENABLE;
ALTER TABLE "${schema}"."PSP" ADD CONSTRAINT "FK_PSP_INT_QUADRATURE" FOREIGN KEY ("FK_INT_QUADRATURE")
	  REFERENCES "${schema}"."INTERMEDIARI_PSP" ("OBJ_ID") ENABLE;
ALTER TABLE "${schema}"."INFORMATIVE_CONTO_ACCREDITO_MASTER" ADD CONSTRAINT "FK_BINARY_FILE" FOREIGN KEY ("FK_BINARY_FILE")
	  REFERENCES "${schema}"."BINARY_FILE" ("OBJ_ID") ENABLE;
ALTER TABLE "${schema}"."INFORMATIVE_CONTO_ACCREDITO_MASTER" ADD CONSTRAINT "FK_INFORMATIVE_CONTO_ACCREDITO_MASTER_PA" FOREIGN KEY ("FK_PA")
	  REFERENCES "${schema}"."PA" ("OBJ_ID") ENABLE;
ALTER TABLE "${schema}"."INFORMATIVE_PA_FASCE" ADD CONSTRAINT "FK_INFORMATIVE_PA_DETAIL" FOREIGN KEY ("FK_INFORMATIVA_PA_DETAIL")
	  REFERENCES "${schema}"."INFORMATIVE_PA_DETAIL" ("OBJ_ID") ENABLE;
ALTER TABLE "${schema}"."CDI_INFORMAZIONI_SERVIZIO" ADD CONSTRAINT "FK_CDI_INFORMAZIONI_SERVIZIO_TO_CDI_DETAIL" FOREIGN KEY ("FK_CDI_DETAIL")
	  REFERENCES "${schema}"."CDI_DETAIL" ("OBJ_ID") ENABLE;
ALTER TABLE "${schema}"."CANALI_NODO" ADD CONSTRAINT "FK_CANALI_SERV_PLUGIN" FOREIGN KEY ("ID_SERV_PLUGIN")
	  REFERENCES "${schema}"."WFESP_PLUGIN_CONF" ("ID_SERV_PLUGIN") ENABLE;
ALTER TABLE "${schema}"."PSP_CANALE_TIPO_VERSAMENTO" ADD CONSTRAINT "FK_PSP_CANALE_TIPO_VERSAMENTO_PSP" FOREIGN KEY ("FK_PSP")
	  REFERENCES "${schema}"."PSP" ("OBJ_ID") ENABLE;
ALTER TABLE "${schema}"."PSP_CANALE_TIPO_VERSAMENTO" ADD CONSTRAINT "FK_CANALE_TIPO_VERSAMENTO" FOREIGN KEY ("FK_CANALE_TIPO_VERSAMENTO")
	  REFERENCES "${schema}"."CANALE_TIPO_VERSAMENTO" ("OBJ_ID") ENABLE;
ALTER TABLE "${schema}"."CDI_FASCIA_COSTO_SERVIZIO" ADD CONSTRAINT "FK_CDI_FASCIA_COSTO_SERVIZIO_TO_CDI_DETAIL" FOREIGN KEY ("FK_CDI_DETAIL")
	  REFERENCES "${schema}"."CDI_DETAIL" ("OBJ_ID") ENABLE;
ALTER TABLE "${schema}"."CDI_MASTER" ADD CONSTRAINT "FK_CDI_MASTER_TO_BINARY_FILE" FOREIGN KEY ("FK_BINARY_FILE")
	  REFERENCES "${schema}"."BINARY_FILE" ("OBJ_ID") ENABLE;
ALTER TABLE "${schema}"."CDI_MASTER" ADD CONSTRAINT "FK_CDI_MASTER_TO_PSP" FOREIGN KEY ("FK_PSP")
	  REFERENCES "${schema}"."PSP" ("OBJ_ID") ENABLE;
ALTER TABLE "${schema}"."STAZIONI" ADD CONSTRAINT "FK_STAZIONI_INTERMEDIARI_PA" FOREIGN KEY ("FK_INTERMEDIARIO_PA")
	  REFERENCES "${schema}"."INTERMEDIARI_PA" ("OBJ_ID") ENABLE;
ALTER TABLE "${schema}"."CANALI" ADD CONSTRAINT "FK_CANALI_INTERMEDIARI_PSP" FOREIGN KEY ("FK_INTERMEDIARIO_PSP")
	  REFERENCES "${schema}"."INTERMEDIARI_PSP" ("OBJ_ID") ENABLE;
ALTER TABLE "${schema}"."CANALI" ADD CONSTRAINT "FK_CANALI_NODO" FOREIGN KEY ("FK_CANALI_NODO")
	  REFERENCES "${schema}"."CANALI_NODO" ("OBJ_ID") ENABLE;
ALTER TABLE "${schema}"."CDI_DETAIL" ADD CONSTRAINT "FK_CDI_DETAIL_TO_CDI_MASTER" FOREIGN KEY ("FK_CDI_MASTER")
	  REFERENCES "${schema}"."CDI_MASTER" ("OBJ_ID") ENABLE;
ALTER TABLE "${schema}"."CDI_DETAIL" ADD CONSTRAINT "FK_CDI_DETAIL_TO_PSP_CANALE_TIPO_VERSAMENTO" FOREIGN KEY ("FK_PSP_CANALE_TIPO_VERSAMENTO")
	  REFERENCES "${schema}"."PSP_CANALE_TIPO_VERSAMENTO" ("OBJ_ID") ENABLE;
ALTER TABLE "${schema}"."PA_STAZIONE_PA" ADD CONSTRAINT "FK_PA_STAZIONE_PA_PA" FOREIGN KEY ("FK_PA")
	  REFERENCES "${schema}"."PA" ("OBJ_ID") ENABLE;
ALTER TABLE "${schema}"."PA_STAZIONE_PA" ADD CONSTRAINT "FK_PA_STAZIONE_PA_STAZIONE" FOREIGN KEY ("FK_STAZIONE")
	  REFERENCES "${schema}"."STAZIONI" ("OBJ_ID") ENABLE;
ALTER TABLE "${schema}"."INFORMATIVE_PA_MASTER" ADD CONSTRAINT "FK_INFORMATIVE_PA_MASTER_PA" FOREIGN KEY ("FK_PA")
	  REFERENCES "${schema}"."PA" ("OBJ_ID") ENABLE;
ALTER TABLE "${schema}"."INFORMATIVE_PA_MASTER" ADD CONSTRAINT "FK_INFORMATIVE_PA_MASTER_BINARY_FILE" FOREIGN KEY ("FK_BINARY_FILE")
	  REFERENCES "${schema}"."BINARY_FILE" ("OBJ_ID") ENABLE;
ALTER TABLE "${schema}"."CDI_PREFERENCES" ADD CONSTRAINT "FK_INFORMATIVA_DETAIL_TO_CDI_DETAIL" FOREIGN KEY ("FK_INFORMATIVA_DETAIL")
	  REFERENCES "${schema}"."CDI_DETAIL" ("OBJ_ID") ENABLE;
ALTER TABLE "${schema}"."INFORMATIVE_CONTO_ACCREDITO_DETAIL" ADD CONSTRAINT "FK_INFORMATIVA_CONTO_ACCREDITO_MASTER" FOREIGN KEY ("FK_INFORMATIVA_CONTO_ACCREDITO_MASTER")
	  REFERENCES "${schema}"."INFORMATIVE_CONTO_ACCREDITO_MASTER" ("OBJ_ID") ENABLE;
ALTER TABLE "${schema}"."CANALE_TIPO_VERSAMENTO" ADD CONSTRAINT "FK_CANALE_TIPO_VERSAMENTO_CANALI" FOREIGN KEY ("FK_CANALE")
	  REFERENCES "${schema}"."CANALI" ("OBJ_ID") ENABLE;
ALTER TABLE "${schema}"."CANALE_TIPO_VERSAMENTO" ADD CONSTRAINT "FK_CANALE_TIPO_VERSAMENTO_TIPO_VERSAMENTO" FOREIGN KEY ("FK_TIPO_VERSAMENTO")
	  REFERENCES "${schema}"."TIPI_VERSAMENTO" ("OBJ_ID") ENABLE;
ALTER TABLE "${schema}"."CODIFICHE_PA" ADD CONSTRAINT "FK_CODIFICHE_PA_PA" FOREIGN KEY ("FK_PA")
	  REFERENCES "${schema}"."PA" ("OBJ_ID") ENABLE;
ALTER TABLE "${schema}"."CODIFICHE_PA" ADD CONSTRAINT "FK_CODIFICHE" FOREIGN KEY ("FK_CODIFICA")
	  REFERENCES "${schema}"."CODIFICHE" ("OBJ_ID") ENABLE;
ALTER TABLE "${schema}"."INFORMATIVE_PA_DETAIL" ADD CONSTRAINT "FK_INFORMATIVE_PA_MASTER" FOREIGN KEY ("FK_INFORMATIVA_PA_MASTER")
	  REFERENCES "${schema}"."INFORMATIVE_PA_MASTER" ("OBJ_ID") ENABLE;
ALTER TABLE "${schema}"."PA" ADD CONSTRAINT "FK_PA_INT_QUADRATURE" FOREIGN KEY ("FK_INT_QUADRATURE")
	  REFERENCES "${schema}"."INTERMEDIARI_PA" ("OBJ_ID") ENABLE;