CREATE TABLE "${schema}"."PSP"
   ( "OBJ_ID" NUMBER DEFAULT "${schema}"."PSP_SEQ".NEXTVAL,
	"ID_PSP" VARCHAR2(35 CHAR) NOT NULL ENABLE,
	"ENABLED" CHAR(1 CHAR) NOT NULL ENABLE,
	"ABI" VARCHAR2(5 CHAR),
	"BIC" VARCHAR2(11 CHAR),
	"DESCRIZIONE" VARCHAR2(70 CHAR),
	"RAGIONE_SOCIALE" VARCHAR2(70 CHAR),
	"FK_INT_QUADRATURE" NUMBER(19,0),
	"STORNO_PAGAMENTO" NUMBER(19,0) DEFAULT '0' NOT NULL ENABLE,
	"FLAG_REPO_COMMISSIONE_CARICO_PA" CHAR(1 CHAR),
	"EMAIL_REPO_COMMISSIONE_CARICO_PA" VARCHAR2(255 CHAR),
	"CODICE_MYBANK" VARCHAR2(35 CHAR),
	"MARCA_BOLLO_DIGITALE" NUMBER(*,0) NOT NULL ENABLE,
	"AGID_PSP" CHAR(1 CHAR) NOT NULL ENABLE,
	"PSP_NODO" CHAR(1 CHAR) DEFAULT 'N' NOT NULL ENABLE,
	"PSP_AVV" CHAR(1 CHAR) DEFAULT 'N' NOT NULL ENABLE,
	"CODICE_FISCALE" VARCHAR2(16 CHAR),
	"VAT_NUMBER" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."CONFIGURATION_KEYS"
   (	"CONFIG_CATEGORY" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"CONFIG_KEY" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"CONFIG_VALUE" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"CONFIG_DESCRIPTION" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."PDD"
   ( "OBJ_ID" NUMBER DEFAULT "${schema}"."PDD_SEQ".NEXTVAL,
	"ID_PDD" VARCHAR2(35 CHAR) NOT NULL ENABLE,
	"ENABLED" CHAR(1 CHAR) NOT NULL ENABLE,
	"DESCRIZIONE" VARCHAR2(35 CHAR) NOT NULL ENABLE,
	"IP" VARCHAR2(15 CHAR) NOT NULL ENABLE,
	"PORTA" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."AUTH_PERMISSIONS"
   ( "OBJ_ID" NUMBER DEFAULT "${schema}"."AUTH_PERMISSIONS_SEQ".NEXTVAL,
	"PERM_ACTION" VARCHAR2(250 CHAR),
	"PERM_TYPE" VARCHAR2(1 CHAR) NOT NULL ENABLE,
	"PERM_RECIPIENT" VARCHAR2(50 CHAR) NOT NULL ENABLE,
	"PERM_TARGET" VARCHAR2(250 CHAR)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."PA"
   ( "OBJ_ID" NUMBER DEFAULT "${schema}"."PA_SEQ".NEXTVAL,
	"ID_DOMINIO" VARCHAR2(35 CHAR) NOT NULL ENABLE,
	"ENABLED" CHAR(1 CHAR) NOT NULL ENABLE,
	"DESCRIZIONE" VARCHAR2(70 CHAR),
	"RAGIONE_SOCIALE" VARCHAR2(70 CHAR),
	"FK_INT_QUADRATURE" NUMBER,
	"FLAG_REPO_COMMISSIONE_CARICO_PA" CHAR(1 CHAR) NOT NULL ENABLE,
	"EMAIL_REPO_COMMISSIONE_CARICO_PA" VARCHAR2(255 CHAR),
	"INDIRIZZO_DOMICILIO_FISCALE" VARCHAR2(255 CHAR),
	"SIGLA_PROVINCIA_DOMICILIO_FISCALE" VARCHAR2(2 CHAR),
	"COMUNE_DOMICILIO_FISCALE" VARCHAR2(255 CHAR),
	"DENOMINAZIONE_DOMICILIO_FISCALE" VARCHAR2(255 CHAR),
	"PAGAMENTO_PRESSO_PSP" CHAR(1 CHAR) NOT NULL ENABLE,
	"RENDICONTAZIONE_FTP" CHAR(1 CHAR) NOT NULL ENABLE,
	"RENDICONTAZIONE_ZIP" CHAR(1 CHAR) NOT NULL ENABLE,
	"REVOCA_PAGAMENTO" NUMBER DEFAULT 0 NOT NULL ENABLE,
	"CAP_DOMICILIO_FISCALE" CHAR(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."STAZIONI"
   ( "OBJ_ID" NUMBER DEFAULT "${schema}"."STAZIONI_SEQ".NEXTVAL,
	"ID_STAZIONE" VARCHAR2(35 CHAR) NOT NULL ENABLE,
	"ENABLED" CHAR(1 CHAR) NOT NULL ENABLE,
	"IP" VARCHAR2(100 CHAR),
	"NEW_PASSWORD" VARCHAR2(15 CHAR),
	"PASSWORD" VARCHAR2(15 CHAR),
	"PORTA" NUMBER NOT NULL ENABLE,
	"PROTOCOLLO" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"REDIRECT_IP" VARCHAR2(100 CHAR),
	"REDIRECT_PATH" VARCHAR2(100 CHAR),
	"REDIRECT_PORTA" NUMBER,
	"REDIRECT_QUERY_STRING" VARCHAR2(255 CHAR),
	"SERVIZIO" VARCHAR2(100 CHAR),
	"RT_ENABLED" CHAR(1 CHAR) NOT NULL ENABLE,
	"SERVIZIO_POF" VARCHAR2(100 CHAR),
	"FK_INTERMEDIARIO_PA" NUMBER NOT NULL ENABLE,
	"REDIRECT_PROTOCOLLO" VARCHAR2(35 CHAR),
	"PROTOCOLLO_4MOD" VARCHAR2(255 CHAR),
	"IP_4MOD" VARCHAR2(100 CHAR),
	"PORTA_4MOD" NUMBER,
	"SERVIZIO_4MOD" VARCHAR2(255 CHAR),
	"PROXY_ENABLED" CHAR(1 CHAR),
	"PROXY_HOST" VARCHAR2(100 CHAR),
	"PROXY_PORT" NUMBER,
	"PROXY_USERNAME" VARCHAR2(15 CHAR),
	"PROXY_PASSWORD" VARCHAR2(15 CHAR),
	"PROTOCOLLO_AVV" VARCHAR2(255 CHAR),
	"IP_AVV" VARCHAR2(100 CHAR),
	"PORTA_AVV" NUMBER,
	"SERVIZIO_AVV" VARCHAR2(255 CHAR),
	"TIMEOUT" NUMBER(19,0) DEFAULT 120 NOT NULL ENABLE,
	"NUM_THREAD" NUMBER(*,0) NOT NULL ENABLE,
	"TIMEOUT_A" NUMBER(19,0) NOT NULL ENABLE,
	"TIMEOUT_B" NUMBER(19,0) NOT NULL ENABLE,
	"TIMEOUT_C" NUMBER(19,0) NOT NULL ENABLE,
	"FLAG_ONLINE" CHAR(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
	"VERSIONE" NUMBER DEFAULT 1.0 NOT NULL ENABLE,
	"SERVIZIO_NMP" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."QUADRATURE_SCHED"
   ( "OBJ_ID" NUMBER DEFAULT "${schema}"."QUADRATURE_SCHED_SEQ".NEXTVAL,
	"ID_SOGGETTO" VARCHAR2(35 CHAR),
	"MODALITA" VARCHAR2(35 CHAR),
	"TIPO_QUAD" VARCHAR2(35 CHAR),
	"DAYS_OF_THE_WEEK_CODE" VARCHAR2(7 CHAR),
	"JOB_START_DATE" TIMESTAMP (6),
	"ENABLED" CHAR(1 BYTE),
	"ON_CLICK" CHAR(1 BYTE),
	"JOB_END_HOUR" TIMESTAMP (6),
	"JOB_START_HOUR" TIMESTAMP (6),
	"TIMESTAMP_LAST_ACTION" TIMESTAMP (6),
	"TIMESTAMP_END" TIMESTAMP (6),
	"TIMESTAMP_BEGIN" TIMESTAMP (6),
	"QUAD_LAST_DATE" TIMESTAMP (6),
	"TYPE_INIZIO_GIORNATA" CHAR(1 CHAR) DEFAULT 'N' NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."CDS_SOGGETTO"
   ( "OBJ_ID" NUMBER DEFAULT "${schema}"."CDS_SOGGETTO_SEQ".NEXTVAL,
	"ID_DOMINIO" VARCHAR2(35 CHAR) NOT NULL ENABLE,
	"DESCRIZIONE_ENTE" VARCHAR2(70 CHAR) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."CDS_SOGGETTO_SERVIZIO"
   ( "OBJ_ID" NUMBER DEFAULT "${schema}"."CDS_SOGGETTO_SERVIZIO_SEQ".NEXTVAL,
	"FK_CDS_SOGGETTO" NUMBER NOT NULL ENABLE,
	"FK_CDS_SERVIZIO" NUMBER NOT NULL ENABLE,
	"DATA_INIZIO_VALIDITA" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."PSP_CANALE_TIPO_VERSAMENTO"
   ( "OBJ_ID" NUMBER DEFAULT "${schema}"."PSP_CANALE_TIPO_VERSAMENTO_SEQ".NEXTVAL,
	"FK_CANALE_TIPO_VERSAMENTO" NUMBER NOT NULL ENABLE,
	"FK_PSP" NUMBER NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."CANALI"
   ( "OBJ_ID" NUMBER DEFAULT "${schema}"."CANALI_SEQ".NEXTVAL,
	"ID_CANALE" VARCHAR2(35 CHAR) NOT NULL ENABLE,
	"ENABLED" CHAR(1 CHAR) NOT NULL ENABLE,
	"IP" VARCHAR2(100 CHAR),
	"NEW_PASSWORD" VARCHAR2(15 CHAR),
	"PASSWORD" VARCHAR2(15 CHAR),
	"PORTA" NUMBER NOT NULL ENABLE,
	"PROTOCOLLO" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"SERVIZIO" VARCHAR2(100 CHAR),
	"DESCRIZIONE" VARCHAR2(70 CHAR),
	"FK_INTERMEDIARIO_PSP" NUMBER NOT NULL ENABLE,
	"PROXY_ENABLED" CHAR(1 CHAR) NOT NULL ENABLE,
	"PROXY_HOST" VARCHAR2(100 CHAR),
	"PROXY_PASSWORD" VARCHAR2(15 CHAR),
	"PROXY_PORT" NUMBER,
	"PROXY_USERNAME" VARCHAR2(15 CHAR),
	"CANALE_NODO" CHAR(1 CHAR) DEFAULT 'N' NOT NULL ENABLE,
	"CANALE_AVV" CHAR(1 CHAR) DEFAULT 'N' NOT NULL ENABLE,
	"FK_CANALI_NODO" NUMBER,
	"TIMEOUT" NUMBER DEFAULT 120 NOT NULL ENABLE,
	"NUM_THREAD" NUMBER(*,0) NOT NULL ENABLE,
	"USE_NEW_FAULT_CODE" CHAR(1 BYTE) NOT NULL ENABLE,
	"TIMEOUT_A" NUMBER(19,0) NOT NULL ENABLE,
	"TIMEOUT_B" NUMBER(19,0) NOT NULL ENABLE,
	"TIMEOUT_C" NUMBER(19,0) NOT NULL ENABLE,
	"SERVIZIO_NMP" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."PA_STAZIONE_PA"
   ( "OBJ_ID" NUMBER DEFAULT "${schema}"."PA_STAZIONE_PA_SEQ".NEXTVAL,
	"PROGRESSIVO" NUMBER,
	"FK_PA" NUMBER NOT NULL ENABLE,
	"FK_STAZIONE" NUMBER NOT NULL ENABLE,
	"AUX_DIGIT" NUMBER,
	"SEGREGAZIONE" NUMBER,
	"QUARTO_MODELLO" CHAR(1 CHAR) NOT NULL ENABLE,
	"STAZIONE_NODO" CHAR(1 CHAR) DEFAULT 'N' NOT NULL ENABLE,
	"STAZIONE_AVV" CHAR(1 CHAR) DEFAULT 'N' NOT NULL ENABLE,
	"BROADCAST" CHAR(1 BYTE) DEFAULT 'N' NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."AUTH_ROLES"
   ( "OBJ_ID" NUMBER DEFAULT "${schema}"."AUTH_ROLES_SEQ".NEXTVAL,
	"OPTLOCK" NUMBER,
	"FUNCTIONAL_ROLE" CHAR(1 CHAR) NOT NULL ENABLE,
	"BUSINESS_ROLE" CHAR(1 CHAR) NOT NULL ENABLE,
	"CONDITIONAL_ROLE" CHAR(1 CHAR) NOT NULL ENABLE,
	"DEFAULT_ROLE" CHAR(1 CHAR) NOT NULL ENABLE,
	"ROLE_NAME" VARCHAR2(100 CHAR) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."AUTH_USERS"
   ( "OBJ_ID" NUMBER DEFAULT "${schema}"."AUTH_USERS_SEQ".NEXTVAL,
	"OPTLOCK" NUMBER,
	"USER_CODE" VARCHAR2(10 CHAR) NOT NULL ENABLE,
	"CREATION_DATE" TIMESTAMP (6),
	"USER_EMAIL" VARCHAR2(100 CHAR),
	"EXPIRY_DATE" TIMESTAMP (6),
	"FAILED_LOGINS" NUMBER(*,0),
	"USER_FIRSTNAME" VARCHAR2(50 CHAR),
	"LAST_LOGIN_DATE" TIMESTAMP (6),
	"USER_PASSWORD" VARCHAR2(100 CHAR) NOT NULL ENABLE,
	"PASSW_EXPIRY_DATE" TIMESTAMP (6),
	"USER_STATUS" VARCHAR2(15 CHAR) NOT NULL ENABLE,
	"USER_SURNAME" VARCHAR2(50 CHAR),
	"USER_NAME" VARCHAR2(50 CHAR) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."AUTH_ROLE_GROUPS"
   (	"ROLE_ID" NUMBER NOT NULL ENABLE,
	"GROUP_ID" NUMBER NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."WFESP_PLUGIN_CONF"
   ( "OBJ_ID" NUMBER DEFAULT "${schema}"."WFESP_PLUGIN_CONF_SEQ".NEXTVAL,
	"ID_SERV_PLUGIN" VARCHAR2(35 CHAR) NOT NULL ENABLE,
	"PROFILO_PAG_CONST_STRING" VARCHAR2(150 CHAR),
	"PROFILO_PAG_SOAP_RULE" VARCHAR2(150 CHAR),
	"PROFILO_PAG_RPT_XPATH" VARCHAR2(150 CHAR),
	"ID_BEAN" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."CODIFICHE"
   ( "OBJ_ID" NUMBER DEFAULT "${schema}"."CODIFICHE_SEQ".NEXTVAL,
	"ID_CODIFICA" VARCHAR2(35 CHAR) NOT NULL ENABLE,
	"DESCRIZIONE" VARCHAR2(35 CHAR)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."INFORMATIVE_PA_FASCE"
   ( "OBJ_ID" NUMBER DEFAULT "${schema}"."INFORMATIVE_PA_FASCE_SEQ".NEXTVAL,
	"ORA_A" VARCHAR2(35 CHAR),
	"ORA_DA" VARCHAR2(35 CHAR),
	"FK_INFORMATIVA_PA_DETAIL" NUMBER NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."CDI_FASCIA_COSTO_SERVIZIO"
   ( "OBJ_ID" NUMBER DEFAULT "${schema}"."CDI_FASCIA_COSTO_SERVIZIO_SEQ".NEXTVAL,
	"IMPORTO_MINIMO" FLOAT(126) NOT NULL ENABLE,
	"IMPORTO_MASSIMO" FLOAT(126) NOT NULL ENABLE,
	"COSTO_FISSO" FLOAT(126) NOT NULL ENABLE,
	"FK_CDI_DETAIL" NUMBER NOT NULL ENABLE,
	"VALORE_COMMISSIONE" FLOAT(126),
	"CODICE_CONVENZIONE" VARCHAR2(35 CHAR)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."TIPI_VERSAMENTO"
   ( "OBJ_ID" NUMBER DEFAULT "${schema}"."TIPI_VERSAMENTO_SEQ".NEXTVAL,
	"DESCRIZIONE" VARCHAR2(35 CHAR),
	"TIPO_VERSAMENTO" VARCHAR2(15 CHAR) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."DENYLIST"
   (	"FK_PSP" NUMBER NOT NULL ENABLE,
	"FK_CANALE" NUMBER NOT NULL ENABLE,
	"FK_PA" NUMBER NOT NULL ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."AUTH_ACCOUNT_ROLES"
   (	"ACCOUNT_ID" NUMBER NOT NULL ENABLE,
	"ROLE_ID" NUMBER NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."CDI_PREFERENCES"
   ( "OBJ_ID" NUMBER DEFAULT "${schema}"."CDI_PREFERENCES_SEQ".NEXTVAL,
	"FK_INFORMATIVA_DETAIL" NUMBER NOT NULL ENABLE,
	"SELLER" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"BUYER" VARCHAR2(255 CHAR),
	"COSTO_CONVENZIONE" NUMBER(*,0) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."FTP_SERVERS"
   ( "OBJ_ID" NUMBER DEFAULT "${schema}"."FTP_SERVERS_SEQ".NEXTVAL,
	"HOST" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"PORT" NUMBER NOT NULL ENABLE,
	"USERNAME" VARCHAR2(35 CHAR) NOT NULL ENABLE,
	"PASSWORD" VARCHAR2(35 CHAR) NOT NULL ENABLE,
	"ROOT_PATH" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"SERVICE" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"TYPE" VARCHAR2(35 CHAR) NOT NULL ENABLE,
	"IN_PATH" VARCHAR2(255 CHAR),
	"OUT_PATH" VARCHAR2(255 CHAR),
	"HISTORY_PATH" VARCHAR2(255 CHAR),
	"ENABLED" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."INFORMATIVE_CONTO_ACCREDITO_MASTER"
   ( "OBJ_ID" NUMBER DEFAULT "${schema}"."INFORMATIVE_CONTO_ACCREDITO_MASTER_SEQ".NEXTVAL,
	"DATA_INIZIO_VALIDITA" TIMESTAMP (6),
	"DATA_PUBBLICAZIONE" TIMESTAMP (6),
	"ID_INFORMATIVA_CONTO_ACCREDITO_PA" VARCHAR2(35 CHAR) NOT NULL ENABLE,
	"RAGIONE_SOCIALE" VARCHAR2(70 CHAR),
	"FK_PA" NUMBER,
	"FK_BINARY_FILE" NUMBER,
	"VERSIONE" VARCHAR2(35 CHAR)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."INTERMEDIARI_PA"
   ( "OBJ_ID" NUMBER DEFAULT "${schema}"."INTERMEDIARI_PA_SEQ".NEXTVAL,
	"ID_INTERMEDIARIO_PA" VARCHAR2(35 CHAR) NOT NULL ENABLE,
	"ENABLED" CHAR(1 CHAR) NOT NULL ENABLE,
	"CODICE_INTERMEDIARIO" VARCHAR2(255 CHAR),
	"FAULT_BEAN_ESTESO" CHAR(1 CHAR) DEFAULT 'N' NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."CANALI_NODO"
   ( "OBJ_ID" NUMBER DEFAULT "${schema}"."CANALI_NODO_SEQ".NEXTVAL,
	"REDIRECT_IP" VARCHAR2(100 CHAR),
	"REDIRECT_PATH" VARCHAR2(100 CHAR),
	"REDIRECT_PORTA" NUMBER,
	"REDIRECT_QUERY_STRING" VARCHAR2(255 CHAR),
	"MODELLO_PAGAMENTO" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"MULTI_PAYMENT" CHAR(1 CHAR) NOT NULL ENABLE,
	"RAGIONE_SOCIALE" VARCHAR2(35 CHAR),
	"RPT_RT_COMPLIANT" CHAR(1 CHAR) NOT NULL ENABLE,
	"WSAPI" VARCHAR2(15 CHAR),
	"REDIRECT_PROTOCOLLO" VARCHAR2(35 CHAR),
	"ID_SERV_PLUGIN" VARCHAR2(35 CHAR),
	"ID_CLUSTER" VARCHAR2(255 CHAR),
	"ID_FESP_INSTANCE" VARCHAR2(275 CHAR),
	"LENTO" CHAR(1 CHAR) NOT NULL ENABLE,
	"RT_PUSH" CHAR(1 CHAR) NOT NULL ENABLE,
	"AGID_CHANNEL" CHAR(1 CHAR) NOT NULL ENABLE,
	"ON_US" CHAR(1 CHAR) NOT NULL ENABLE,
	"CARRELLO_CARTE" CHAR(1 CHAR) NOT NULL ENABLE,
	"RECOVERY" CHAR(1 CHAR) DEFAULT 'N' NOT NULL ENABLE,
	"MARCA_BOLLO_DIGITALE" CHAR(1 BYTE) NOT NULL ENABLE,
	"FLAG_IO" CHAR(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."INFORMATIVE_PA_MASTER"
   ( "OBJ_ID" NUMBER DEFAULT "${schema}"."INFORMATIVE_PA_MASTER_SEQ".NEXTVAL,
	"ID_INFORMATIVA_PA" VARCHAR2(35 CHAR) NOT NULL ENABLE,
	"DATA_INIZIO_VALIDITA" TIMESTAMP (6),
	"DATA_PUBBLICAZIONE" TIMESTAMP (6),
	"FK_PA" NUMBER NOT NULL ENABLE,
	"FK_BINARY_FILE" NUMBER,
	"VERSIONE" VARCHAR2(35 CHAR),
	"PAGAMENTI_PRESSO_PSP" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."INFORMATIVE_CONTO_ACCREDITO_DETAIL"
   ( "OBJ_ID" NUMBER DEFAULT "${schema}"."INFORMATIVE_CONTO_ACCREDITO_DETAIL_SEQ".NEXTVAL,
	"IBAN_ACCREDITO" VARCHAR2(35 CHAR),
	"FK_INFORMATIVA_CONTO_ACCREDITO_MASTER" NUMBER,
	"ID_MERCHANT" VARCHAR2(15 CHAR),
	"CHIAVE_AVVIO" VARCHAR2(255 CHAR),
	"CHIAVE_ESITO" VARCHAR2(255 CHAR),
	"ID_BANCA_SELLER" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."CANALE_TIPO_VERSAMENTO"
   ( "OBJ_ID" NUMBER DEFAULT "${schema}"."CANALE_TIPO_VERSAMENTO_SEQ".NEXTVAL,
	"FK_CANALE" NUMBER NOT NULL ENABLE,
	"FK_TIPO_VERSAMENTO" NUMBER NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."CDI_INFORMAZIONI_SERVIZIO"
   ( "OBJ_ID" NUMBER DEFAULT "${schema}"."CDI_INFORMAZIONI_SERVIZIO_SEQ".NEXTVAL,
	"CODICE_LINGUA" CHAR(2 CHAR) NOT NULL ENABLE,
	"DESCRIZIONE_SERVIZIO" VARCHAR2(140 CHAR) NOT NULL ENABLE,
	"DISPONIBILITA_SERVIZIO" VARCHAR2(140 CHAR) NOT NULL ENABLE,
	"URL_INFORMAZIONI_CANALE" VARCHAR2(255 CHAR),
	"FK_CDI_DETAIL" NUMBER NOT NULL ENABLE,
	"LIMITAZIONI_SERVIZIO" VARCHAR2(140 CHAR)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."TEMPLATE_MARKDOWN"
   (	"NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"CONTENT" VARCHAR2(4000 CHAR) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."SYNC_STATUS"
   ( "OBJ_ID" NUMBER DEFAULT "${schema}"."SYNC_STATUS_SEQ".NEXTVAL,
	"SNAPSHOT_VERSION" NUMBER(19,0),
	"STATUS" CHAR(1 BYTE),
	"TIMESTAMP_SNAPSHOT" TIMESTAMP (6),
	"SYNC_FESP" CHAR(1 BYTE),
	"SYNC_PM" CHAR(1 BYTE),
	"SYNC_NODO_4" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."INTERMEDIARI_PSP"
   ( "OBJ_ID" NUMBER DEFAULT "${schema}"."INTERMEDIARI_PSP_SEQ".NEXTVAL,
	"ID_INTERMEDIARIO_PSP" VARCHAR2(35 CHAR) NOT NULL ENABLE,
	"ENABLED" CHAR(1 CHAR) NOT NULL ENABLE,
	"CODICE_INTERMEDIARIO" VARCHAR2(255 CHAR),
	"INTERMEDIARIO_AVV" CHAR(1 CHAR) DEFAULT 'N' NOT NULL ENABLE,
	"INTERMEDIARIO_NODO" CHAR(1 CHAR) DEFAULT 'N' NOT NULL ENABLE,
	"FAULT_BEAN_ESTESO" CHAR(1 CHAR) DEFAULT 'N' NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."CDS_SERVIZIO"
   ( "OBJ_ID" NUMBER DEFAULT "${schema}"."CDS_SERVIZIO_SEQ".NEXTVAL,
	"ID_SERVIZIO" VARCHAR2(5 CHAR) NOT NULL ENABLE,
	"DESCRIZIONE_SERVIZIO" VARCHAR2(70 CHAR) NOT NULL ENABLE,
	"XSD_RIFERIMENTO" VARCHAR2(35 CHAR) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."GDE_CONFIG"
   (	"PRIMITIVA" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"TYPE" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"EVENT_HUB" NUMBER(1,0) NOT NULL ENABLE,
	"EVENT_HUB_PAYLOAD" NUMBER(1,0) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."CODIFICHE_PA"
   ( "OBJ_ID" NUMBER DEFAULT "${schema}"."CODIFICHE_PA_SEQ".NEXTVAL,
	"CODICE_PA" VARCHAR2(35 CHAR) NOT NULL ENABLE,
	"FK_CODIFICA" NUMBER NOT NULL ENABLE,
	"FK_PA" NUMBER NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."INFORMATIVE_PA_DETAIL"
   ( "OBJ_ID" NUMBER DEFAULT "${schema}"."INFORMATIVE_PA_DETAIL_SEQ".NEXTVAL,
	"FLAG_DISPONIBILITA" CHAR(1 CHAR) NOT NULL ENABLE,
	"GIORNO" VARCHAR2(35 CHAR),
	"TIPO" VARCHAR2(35 CHAR),
	"FK_INFORMATIVA_PA_MASTER" NUMBER NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}" ;
CREATE TABLE "${schema}"."CDI_MASTER"
   ( "OBJ_ID" NUMBER DEFAULT "${schema}"."CDI_MASTER_SEQ".NEXTVAL,
	"ID_INFORMATIVA_PSP" VARCHAR2(35 CHAR) NOT NULL ENABLE,
	"DATA_INIZIO_VALIDITA" TIMESTAMP (6),
	"DATA_PUBBLICAZIONE" TIMESTAMP (6),
	"LOGO_PSP" BLOB,
	"URL_INFORMAZIONI_PSP" VARCHAR2(255 CHAR),
	"MARCA_BOLLO_DIGITALE" NUMBER NOT NULL ENABLE,
	"STORNO_PAGAMENTO" NUMBER NOT NULL ENABLE,
	"FK_PSP" NUMBER NOT NULL ENABLE,
	"FK_BINARY_FILE" NUMBER NOT NULL ENABLE,
	"VERSIONE" VARCHAR2(35 CHAR),
	"URL_INFORMATIVA_PSP" VARCHAR2(255 CHAR),
	"URL_CONVENZIONI_PSP" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}"
 LOB ("LOGO_PSP") STORE AS SECUREFILE (
  TABLESPACE "${tablespaceLob}" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
CREATE TABLE "${schema}"."ELENCO_SERVIZI"
   ( "OBJ_ID" NUMBER DEFAULT "${schema}"."ELENCO_SERVIZI_SEQ".NEXTVAL,
	"PSP_ID" VARCHAR2(35 CHAR),
	"FLUSSO_ID" VARCHAR2(35 CHAR),
	"PSP_RAG_SOC" VARCHAR2(255 CHAR),
	"PSP_FLAG_STORNO" CHAR(1 BYTE),
	"PSP_FLAG_BOLLO" CHAR(1 BYTE),
	"INTM_ID" VARCHAR2(35 CHAR),
	"CANALE_ID" VARCHAR2(35 CHAR),
	"NOME_SERVIZIO" VARCHAR2(35 CHAR),
	"CANALE_MOD_PAG" NUMBER(*,0),
	"TIPO_VERS_COD" VARCHAR2(255 CHAR),
	"CODICE_LINGUA" CHAR(2 BYTE),
	"INF_COND_EC_MAX" VARCHAR2(35 CHAR),
	"INF_DESC_SERV" VARCHAR2(511 CHAR),
	"INF_DISP_SERV" VARCHAR2(511 CHAR),
	"INF_URL_CANALE" VARCHAR2(255 CHAR),
	"IMPORTO_MINIMO" FLOAT(126),
	"IMPORTO_MASSIMO" FLOAT(126),
	"COSTO_FISSO" FLOAT(126),
	"TIMESTAMP_INS" TIMESTAMP (6),
	"DATA_VALIDITA" TIMESTAMP (6),
	"LOGO_PSP" BLOB,
	"TAGS" VARCHAR2(135 CHAR),
	"LOGO_SERVIZIO" BLOB,
	"CANALE_APP" CHAR(1 BYTE),
	"ON_US" CHAR(1 BYTE),
	"CARRELLO_CARTE" CHAR(1 BYTE),
	"CODICE_ABI" VARCHAR2(5 CHAR),
	"CODICE_MYBANK" VARCHAR2(35 CHAR),
	"CODICE_CONVENZIONE" VARCHAR2(35 CHAR),
	"FLAG_IO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}"
 LOB ("LOGO_PSP") STORE AS SECUREFILE (
  TABLESPACE "${tablespaceLob}" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT))
 LOB ("LOGO_SERVIZIO") STORE AS SECUREFILE (
  TABLESPACE "${tablespaceLob}" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
CREATE TABLE "${schema}"."CACHE"
   (	"ID" VARCHAR2(20 CHAR) NOT NULL ENABLE,
	"TIME" TIMESTAMP (6) NOT NULL ENABLE,
	"CACHE" BLOB NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}"
 LOB ("CACHE") STORE AS SECUREFILE (
  TABLESPACE "${tablespaceLob}" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
CREATE TABLE "${schema}"."CDI_DETAIL"
   ( "OBJ_ID" NUMBER DEFAULT "${schema}"."CDI_DETAIL_SEQ".NEXTVAL,
	"NOME_SERVIZIO" VARCHAR2(35 CHAR) NOT NULL ENABLE,
	"PRIORITA" NUMBER NOT NULL ENABLE,
	"MODELLO_PAGAMENTO" NUMBER NOT NULL ENABLE,
	"FK_CDI_MASTER" NUMBER NOT NULL ENABLE,
	"FK_PSP_CANALE_TIPO_VERSAMENTO" NUMBER NOT NULL ENABLE,
	"CANALE_APP" NUMBER,
	"TAGS" VARCHAR2(135 CHAR),
	"LOGO_SERVIZIO" BLOB
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}"
 LOB ("LOGO_SERVIZIO") STORE AS SECUREFILE (
  TABLESPACE "${tablespaceLob}" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
CREATE TABLE "${schema}"."BINARY_FILE"
   ( "OBJ_ID" NUMBER DEFAULT "${schema}"."BINARY_FILE_SEQ".NEXTVAL,
	"FILE_CONTENT" BLOB NOT NULL ENABLE,
	"FILE_HASH" BLOB NOT NULL ENABLE,
	"FILE_SIZE" NUMBER NOT NULL ENABLE,
	"SIGNATURE_TYPE" VARCHAR2(30 CHAR),
	"XML_FILE_CONTENT" CLOB
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "${tablespaceData}"
 LOB ("FILE_CONTENT") STORE AS SECUREFILE (
  TABLESPACE "${tablespaceLob}" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT))
 LOB ("FILE_HASH") STORE AS SECUREFILE (
  TABLESPACE "${tablespaceLob}" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT))
 LOB ("XML_FILE_CONTENT") STORE AS SECUREFILE (
  TABLESPACE "${tablespaceLob}" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;