alter session set "_ORACLE_SCRIPT"=true;

CREATE USER NODO4_CFG IDENTIFIED BY NODO4_CFG;
GRANT ALL PRIVILEGES TO NODO4_CFG;
ALTER USER NODO4_CFG QUOTA UNLIMITED ON USERS

CREATE TABLESPACE NODO4_CFG_DATA
    DATAFILE '/opt/oracle/oradata/ORCLCDB/ORCLPDB1/NODO4_CFG_DATA.dbf'
    SIZE 5m AUTOEXTEND ON;

CREATE TABLESPACE NODO4_CFG_TABLESPACE
    DATAFILE '/opt/oracle/oradata/ORCLCDB/ORCLPDB1/NODO4_CFG_TABLESPACE.dbf'
    SIZE 5m AUTOEXTEND ON;

CREATE TABLESPACE NODO4_CFG_LOB
    DATAFILE '/opt/oracle/oradata/ORCLCDB/ORCLPDB1/NODO4_CFG_LOB.dbf'
    SIZE 5m AUTOEXTEND ON;

CREATE TABLESPACE NODO4_CFG_IDX
    DATAFILE '/opt/oracle/oradata/ORCLCDB/ORCLPDB1/NODO4_CFG_IDX.dbf'
    SIZE 5m AUTOEXTEND ON;

exit;
