package it.gov.pagopa.apiconfig.datamigration.enumeration;

import lombok.extern.slf4j.Slf4j;

@Slf4j
public enum StepName {

    START,
    EXECUTE_INTERMEDIARIPA_TABLE_MIGRATION,
    EXECUTE_PA_TABLE_MIGRATION,
    EXECUTE_STAZIONI_TABLE_MIGRATION,
    EXECUTE_PASTAZIONEPA_TABLE_MIGRATION,
    EXECUTE_CODIFICHE_TABLE_MIGRATION,
    EXECUTE_CODIFICHEPA_TABLE_MIGRATION,
    EXECUTE_BINARYFILE_TABLE_MIGRATION,
    EXECUTE_IBANVALIDIPERPA_TABLE_MIGRATION,
    EXECUTE_INFORMATIVECONTOACCREDITOMASTER_TABLE_MIGRATION,
    EXECUTE_INFORMATIVECONTOACCREDITODETAIL_TABLE_MIGRATION,
    EXECUTE_INFORMATIVEPAMASTER_TABLE_MIGRATION,
    EXECUTE_INFORMATIVEPADETAIL_TABLE_MIGRATION,
    EXECUTE_INFORMATIVEPAFASCE_TABLE_MIGRATION,
    EXECUTE_INTERMEDIARIPSP_TABLE_MIGRATION,
    EXECUTE_PSP_TABLE_MIGRATION,
    EXECUTE_CANALINODO_TABLE_MIGRATION,
    EXECUTE_CANALI_TABLE_MIGRATION,
    EXECUTE_TIPIVERSAMENTO_TABLE_MIGRATION,
    EXECUTE_CANALETIPOVERSAMENTO_TABLE_MIGRATION,
    EXECUTE_PSPCANALETIPOVERSAMENTO_TABLE_MIGRATION,
    EXECUTE_DIZIONARIOMETADATI_TABLE_MIGRATION,
    EXECUTE_CDIMASTER_TABLE_MIGRATION,
    EXECUTE_CDIDETAIL_TABLE_MIGRATION,
    EXECUTE_CDIFASCIACOSTOSERVIZIO_TABLE_MIGRATION,
    EXECUTE_CDIINFORMAZIONISERVIZIO_TABLE_MIGRATION,
    EXECUTE_CDIPREFERENCES_TABLE_MIGRATION,
    EXECUTE_ELENCOSERVIZI_TABLE_MIGRATION,
    EXECUTE_CDSCATEGORIE_TABLE_MIGRATION,
    EXECUTE_CDSSOGGETTO_TABLE_MIGRATION,
    EXECUTE_CDSSERVIZIO_TABLE_MIGRATION,
    EXECUTE_CDSSOGGETTOSERVIZIO_TABLE_MIGRATION,
    EXECUTE_CONFIGURATIONKEYS_TABLE_MIGRATION,
    EXECUTE_WFESPPLUGINCONN_TABLE_MIGRATION,
    EXECUTE_FTPSERVER_TABLE_MIGRATION,
    EXECUTE_PDD_TABLE_MIGRATION,
    EXECUTE_GDECONFIG_TABLE_MIGRATION,
    EXECUTE_QUADRATURESCHED_TABLE_MIGRATION,
    ERROR,
    END;
}
